#+OPTIONS: toc:nil H:10 tex:t num:0 author:nil date:nil
#+TITLE:
#+STARTUP: odd hidestars indent
#+LATEX_CLASS: article
#+LATEX_HEADER: \input{page_setup.tex}
| martin.frackerjr@gmail.com | *Martin Fracker, Jr.*   | 1501 Copperfield Pkwy, #113 |
| (979)-676-5680             | www.martinfrackerjr.com | College Station, TX 77845 |

* EXPERIENCE
** Improving - College Station, TX

/Associate Consultant, Apr 2016-Present/\\

As a technical consultant working for a variety of clients, made significant
contributions to various web applications, including an application to keep
track of job candidates, as well as a loan and insurance analysis system. Used
and became familiar with many different kinds of technologies such as ASP.NET
Web API, ASP.NET MVC, Entity Framework, Jenkins, AngularJS, Angular, Vue.js,
ASP.NET Core, Azure, Visual Studio Team Services, Selenium, Protractor.NET,
Twitter Bootstrap, Less, SASS, Typescript, MYSQL DB, and Raven DB.

* CERTIFICATIONS

** Professional Scrum Master I
*Jul 2016-Present*\\

Certified by =Scrum.org=.

* PROJECTS

** Management Operations Web App / Web Developer
*May 2016-June 2018*\\

Worked in a cross-functional scrum team to develop a management operations web
application for a company which provides risk management solutions for
agribusiness. Set up continuous delivery using Jenkin and Azure, later using
Visual Studio Team Services, allowing my team to deploy multiple times per week.
Interested in upgrading the tech stack, team looked into Vue.js, Angular and
.NET core, and Docker. Using the Agile Scrum methodology together with
test-driven development and technologies such as AngularJS, Vue.js, Angular,
ASP.NET Web API, .NET Core, Jasmine, Jenkins, Azure, Visual Studio Team
Services, Docker, Selenium, Protractor.NET, Twitter Bootstrap, and Entity
Framework, my role was that of a full stack developer.

** Interview Web App / Web Developer
*Apr-May 2016*\\

Configured, designed, and developed the initial iteration of a web application
that would allow hiring staff to record and view candidate details online. Using
technologies such as ASP.NET MVC, Highway Data, RavenDB, and Twitter Bootstrap,
my role was that of a full stack developer.

* COMPUTER SKILLS

*Web Frameworks*: Express, Vue.js, Angular, AngularJS, ASP.NET MVC, ASP.NET Core\\
*DevOps*: Docker, Coveralls, Travis, Jenkins, Visual Studio Team Services, Azure, Heroku\\
*Languages*: C, C++, C#, Ruby, Java, Javascript, Bash, Haskell, Lua, LaTeX.\\
*Applications*: Visual Studio, Emacs, Vim, Unity 3D, Git, JetBrains.\\
*Operating Systems*: Linux, Unix, Mac OSX, Windows.

* EDUCATION
** Texas A&M University - College Station, TX

/B.S., Computer Science, Started Aug 2013/\\
Major GPA: 3.85\\
Overall GPA: 3.4\\
Graduated May 2017.\\
